# Generated by Django 4.1.3 on 2022-12-18 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=8)),
                ('release_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('release_year', models.IntegerField()),
                ('source', models.CharField(max_length=99)),
                ('console_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.console')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('console_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.console')),
            ],
        ),
        migrations.CreateModel(
            name='Cheat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=64)),
                ('notes', models.TextField()),
                ('flag_data', models.JSONField(blank=True, null=True)),
                ('domain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.domain')),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.game')),
            ],
        ),
    ]
