# Generated by Django 4.1.3 on 2022-12-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheat',
            name='flag_data',
        ),
    ]
